services:
minarca-server:
  container_name: cn_minarca-server
  image: ikus060/minarca-server:6.0.0b9.dev14-g327cbdc-debian12
  ports:
    - "8080:8080"
    - "2222:22"
  volumes:
    # Location of the backups
    - ./backups:/backups
    # Configuration file and local database
    - ./conf:/etc/minarca
    # Application logs
    - ./logs:/var/log/minarca
  restart: always
  environment:
    # Define the URL to be used by users to connect to this container port 8080 running the webserver.
    # This is optional and only required if a reverse proxy is used.
    #MINARCA_EXTERNAL_URL: https://minarca.mycompany.com
    # Define the hostname and IP address to be used by Minarca Agent to connect to this container on port 2222 running SSH Server.
    # This is optional and only required if the port used for SSH is not 22.
    MINARCA_MINARCA_REMOTE_HOST: 192.168.xx.xx:2222