services:
  jdownloader-2:
    image: jlesage/jdownloader-2:v25.02.1
    container_name: jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - ./jdownloader-2:/config:rw
      - ./Downloads:/output:rw
    restart: unless-stopped
