services:
  adguardhome:
    image: adguard/adguardhome:v0.107.46
    container_name: cn_AdGuard_home
    network_mode: host
    ports:
      # Plain DNS
      - 53:53
      # DHCP Server
      - 67:67/udp
      - 68:68/udp
      # AdGuard Home Admin Panel as well as DNS-over-HTTPS
      - 80:80/tcp
      - 443:443/tcp
      - 3000:3000/tcp
      # DNS-over-TLS
      - 853:853/tcp
      # DNS-over-QUIC
      - 853:853/udp
      - 784:784/udp
      - 8853:8853/udp
      # DNS-over-QUIC
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: always