#   mkdir -p ~/endscom/filebrowser && cd ~/endscom/filebrowser && touch filebrowser.db .filebrowser.json & nano .filebrowser.json

# {
#   "port": 80,
#   "baseURL": "",
#   "address": "",
#   "log": "stdout",
#   "database": "/database.db",
#   "root": "/srv"
# }


services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: cn_filebrowser
    ports:
      - "8080:80"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - /path/to/root:/srv
      - /path/to/filebrowser.db:/database/filebrowser.db
      - /path/to/settings.json:/config/settings.json
  homer:
    image: b4bz/homer:latest
    container_name: cn_homer
    ports:
      - "3000:8080"
    volumes:
      - ~/Devs/homer:/www/assets
    restart: always

  app-synapse:
    image: matrixdotorg/synapse
    container_name: cn_slack
    restart: always
    ports:
      - "8008:8008"
    volumes:
      - ./synapse-data:/data
  snipe-it:
    image: lscr.io/linuxserver/snipe-it:6.1.2
    container_name: cn_snipe-it
    environment:
      - APP_URL=http://192.168.xx.xx:8200
      - MYSQL_PORT_3306_TCP_ADDR=192.168.1.6
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=db_snipeit
      - MYSQL_USER=root
      - MYSQL_PASSWORD=a7m1425.
    volumes:
      - ./snipe_data:/config
    ports:
      - "8200:80"

  send:
    container_name: cn_send
    image: registry.gitlab.com/timvisee/send:latest
    volumes:
      - ./uploads:/uploads
    environment:
      - NODE_ENV=production
      - DETECT_BASE_URL=true
      - REDIS_HOST=192.168.x.x
      - REDIS_PORT=6379
      - REDIS_PASSWORD=<Cambiame>
      - FILE_DIR=/uploads
      - EXPIRE_TIMES_SECONDS=3600,86400,604800,2592000,31536000
      - DEFAULT_EXPIRE_SECONDS=3600
      - MAX_EXPIRE_SECONDS=31536000
      - DOWNLOAD_COUNTS=1,2,5,10,15,25,50,100,1000
      - MAX_DOWNLOADS=1000
      - MAX_FILE_SIZE=21384995840
    ports:
      - "1443:1443"


  minecraft-server:
    image: itzg/minecraft-server
    container_name : cn_mc-server
    ports:
      - 25565:25565
      - 19132:19132
    environment:
      EULA: "TRUE"
      TYPE: "BUKKIT"
      OPS: "ButterNPants"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-server-data:/data


  uptime-kuma:
    container_name: cn_uptime-kuma
    image: louislam/uptime-kuma:1.23.13
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - './uptime-kuma-data:/app/data'





  # vsftpd:
  #   image: panubo/vsftpd
  #   container_name: cn_vsftpd
  #   environment:
  #     - FTP_USER=jellyfin
  #     - FTP_PASSWORD=a7m1425.
  #   volumes:
  #     - ./vsftpd:/srv
  #   expose:
  #     - 21
  #   network_mode: host

  minio:
    #image: minio/minio:RELEASE.2024-05-10T01-41-38Z-cpuv1
    image: quay.io/minio/minio:latest
    container_name: cn_minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: name_usr
      MINIO_ROOT_PASSWORD: pass_user
    command: server --console-address ":9090" /data
    deploy:
        resources:
          limits:
            memory: 2GB
            cpus: '1.50'
          reservations:
            memory: 500MB

